name: "UC Environment Request"
description: "Use this form to request a new environment setup"
title: "[Environment Request]  "
labels: 
  - environment-request
body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the details for the environment request below:

  - type: input
    id: environment_identifier
    attributes:
      label: Environment Identifier
      description: "Enter the environment identifier. Options: dev, stg, nonprod, sbx, prod."
    validations:
      required: true
      
  - type: dropdown
    id: azure_region
    attributes:
      label: Azure Region
      description: "Select the Azure region."
      
    validations:
      required: true
 

  - type: input
    id: business_unit
    attributes:
      label: Business Unit
      description: "Enter the business unit."
      placeholder: "e.g., Sales, IT, HR"
     

  - type: input
    id: access_connector_id
    attributes:
      label: Access Connector ID
      description: "Enter the Access Connector ID. It should be in the format `/subscriptions/xxxx`."
      placeholder: "/subscriptions/xxxx"
    validations:
      required: true  

  - type: input
    id: user_assigned_managed_identity
    attributes:
      label: User Assigned Managed Identity
      description: "Enter the user-assigned managed identity."
      placeholder: "e.g., my-managed-identity"
    validations:
      required: true
      
  - type: input
    id: storage_container_url
    attributes:
      label: Storage Container URL
      description: "Enter the storage container URL in the format `abfss://<container-name>@<storage-container-name>.dfs.core.windows.net`."
      placeholder: "abfss://<container-name>@<storage-container-name>.dfs.core.windows.net"
    validations:
      required: true

  - type: input
    id: owner_group
    attributes:
      label: Owner Group
      description: "Enter the owner group. It should be in the format `azu_xxxxx`."
      placeholder: "azu_xxxxx"
    validations:
      required: true

  - type: input
    id: workspace_name
    attributes:
      label: Workspace Name
      description: "Enter the workspace name. It should not contain the word 'workspace'."
      placeholder: "e.g., my-workspace"
    validations:
      required: true
