name: "Environment Configuration Form"
description: "Please provide the required details for the environment configuration."
title: "Environment Configuration Request"
labels: ["configuration-request"]

body:
  - type: dropdown
    id: environment_identifier
    attributes:
      label: "Environment Identifier"
      options:
        - dev
        - stg
        - nonprod
        - sbx
        - prod
      description: "Select the environment identifier (e.g., dev, stg, nonprod, sbx, prod)"
      required: true

  - type: dropdown
    id: azure_region
    attributes:
      label: "Azure Region"
      options:
        - centralus
        - eastus
        - eastus2
      description: "Select the Azure region (e.g., centralus, eastus, eastus2)"
      required: true

  - type: input
    id: business_unit
    attributes:
      label: "Business Unit"
      description: "Enter the business unit (e.g., any text)"
      placeholder: "e.g., finance, hr"
      required: true

  - type: input
    id: access_connector_id
    attributes:
      label: "Access Connector ID"
      description: "Enter the access connector ID (e.g., /subscriptions/xxxx)"
      placeholder: "/subscriptions/xxxx"
      required: true

  - type: input
    id: user_assigned_managed_identity
    attributes:
      label: "User Assigned Managed Identity"
      description: "Enter the user-assigned managed identity (e.g., any text)"
      placeholder: "e.g., managed-identity-name"
      required: true

  - type: input
    id: storage_container_url
    attributes:
      label: "Storage Container URL"
      description: "Enter the storage container URL in the format: abfss://<container-name>@<storage-container-name>.dfs.core.windows.net"
      placeholder: "e.g., abfss://my-container@my-storage.dfs.core.windows.net"
      required: true

  - type: input
    id: owner_group
    attributes:
      label: "Owner Group"
      description: "Enter the owner group in the format: azu_xxxxx"
      placeholder: "e.g., azu_finance_team"
      required: true

  - type: input
    id: workspace_name
    attributes:
      label: "Workspace Name"
      description: "Enter the workspace name (should not contain 'workspace')"
      placeholder: "e.g., my-workspace"
      required: true
