name: Azure Configuration Request
description: Please provide the following details to request an Azure setup
title: "[Request] Azure Configuration"
body:
  - type: markdown
    attributes:
      value: "Please fill out the following fields for Azure setup validation."

  - type: input
    id: azure_region
    attributes:
      label: Azure Region Name
      placeholder: "e.g., East US, West Europe"
      description: "Provide the Azure region where the resources will be deployed."

  - type: input
    id: connector_id
    attributes:
      label: Connector ID
      placeholder: "e.g., ABC-123"
      description: "Provide the connector ID."

  - type: input
    id: databricks_workspace
    attributes:
      label: Databricks Workspace Name
      placeholder: "e.g., my-databricks-ws"
      description: "Provide the Databricks workspace name."

  - type: input
    id: azure_ad_group
    attributes:
      label: Azure AD Group Name
      placeholder: "e.g., my-ad-group"
      description: "Provide the Azure AD group name."

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes (Optional)
      description: "Any additional notes or comments for the request."
