name: "UC Enablement Intake Request Form"
description: "Fill out the form to request storage configuration"
title: "[USER] UC Enablement"
labels: ["open"]
body:
  - type: dropdown
    id: environment-identifier
    attributes:
      label: "Environment Identifier"
      options:
        - dev
        - stg
        - nonprod
        - sbx
        - prod
      description: "Select the environment identifier"
    validations:
      required: true

  - type: dropdown
    id: azure-region
    attributes:
      label: "Azure Region"
      options:
        - centralus
        - eastus
        - eastus2
      description: "Select Azure region"
      
    validations:
      required: true

  - type: input
    id: business-unit
    attributes:
      label: "Business Unit"
      description: "Enter the business unit (any text)"
      
    validations:
      required: true

  - type: input
    id: access-connector-id
    attributes:
      label: "Access Connector ID"
      description: "Should be in the format /subscriptions/xxxx"
      placeholder: "/subscriptions/xxxx"
      
    validations:
      required: true

  - type: input
    id: user-assigned-managed-identity
    attributes:
      label: "User Assigned Managed Identity"
      description: "Enter the user-assigned managed identity"
      
    validations:
      required: false
  
  - type: input
    id: workspace-name
    attributes:
      label: "Workspace Name"
      description: "Enter the workspace name (it should not contain 'workspace')"
      
    validations:
      required: true

  - type: dropdown
    
    attributes:
      label: "Number of Storage Containers"
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
      description: "Select how many storage containers you want to provide"
  
  
  - type: input
    id: storage-container-url-1
    attributes:
      label: "Storage Container URL 1"
      description: "Enter the storage container URL (abfss://container-name@storage-container-name.dfs.core.windows.net)"
        
  - type: input
    id: storage-container-url-2
    attributes:
      label: "Storage Container URL 2"
      description: "Enter the storage container URL (abfss://container-name@storage-container-name.dfs.core.windows.net)"
   
  
  - type: input
    id: owner-group
    attributes:
      label: "Azure Owner Group Name"
      description: "Enter the owner group (azu_xxxxx)"
    validations:
      required: true  
      
    
