name: Sample Issue Form
description: Capture two values from the user.
title: "[Input Required] Please provide values"
labels: input-required
body:
  - type: input
    id: value_one
    attributes:
      label: "Enter first value"
      placeholder: "First value"
      required: true
  - type: input
    id: value_two
    attributes:
      label: "Enter second value"
      placeholder: "Second value"
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for providing the values!



