name: 03 - Workflow Runners
on: push

jobs:
    ubuntu-echo:
      runs-on: ubuntu-latest
      steps:  
        - name: Show OS
          run: "This job is running on a Ubuntu Runner"
    windows-echo:
        runs-on: windows-latest
        steps:
          - name: Show OS
            run: "This job is running on a Windows Runner"
    
