# .github/workflows/validate_issue.yml
name: Validate Issue Submission

on:
  issues:
    types: [opened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Issue Fields
        id: validate
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          # You can also set these from the issue body or labels
          ENVIRONMENT_IDENTIFIER=$(echo "$ISSUE_BODY" | grep -oP 'environment-identifier: \K.*')
          CONNECTOR_ID=$(echo "$ISSUE_BODY" | grep -oP 'connector-id: \K.*')
          EXTERNAL_LOCATION=$(echo "$ISSUE_BODY" | grep -oP 'external-location: \K.*')
          AZURE_GROUP_ID=$(echo "$ISSUE_BODY" | grep -oP 'azure-group-id: \K.*')

          # Validation checks
          ERROR_MESSAGES=""
          if [[ ! "$ENVIRONMENT_IDENTIFIER" =~ ^(dev|prod)$ ]]; then
              ERROR_MESSAGES+="Invalid environment-identifier. Must be 'dev' or 'prod'.\n"
          fi

          if [[ ! "$CONNECTOR_ID" =~ ^/subscriptions/ ]]; then
              ERROR_MESSAGES+="Invalid connector-id. Must start with '/subscriptions/'.\n"
          fi

          if [[ ! "$EXTERNAL_LOCATION" =~ ^abfss://.* ]]; then
              ERROR_MESSAGES+="Invalid external-location. Must start with 'abfss://'.\n"
          fi

          if [[ ! "$AZURE_GROUP_ID" =~ ^azu_ ]]; then
              ERROR_MESSAGES+="Invalid azure-group-id. Must start with 'azu_'.\n"
          fi

          if [[ -z "$ERROR_MESSAGES" ]]; then
              echo "All fields are valid."
          else
              echo -e "Errors:\n$ERROR_MESSAGES"
              exit 1
          fi

      - name: Approve or Close Issue
        if: ${{ failure() }}
        run: |
          gh issue close ${{ github.event.issue.number }} --body "$ERROR_MESSAGES"
          echo "Issue closed due to validation errors."
          
        if: ${{ success() }}
        run: |
          echo "All fields valid. Proceed to approve or take further actions as necessary."
