# .github/workflows/validate-storage-request.yml
name: "Validate Storage Request"
on:
  issues:
    types: [opened, edited]
env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  LDAP_MS_ID: ${{ secrets.LDAP_MS_ID }}
  LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Issues Template Parser
        id: issues-parser
        uses: issue-ops/parser@v3.0.0
        with: 
          body: ${{ github.event.issue.body }}
          issue-form-template: number.yml

      
      - name: Validate Environment
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: environment-identifier
          token: ${{ secrets.GIT_TOKEN }}
            #echo "::set-output name=environment_identifier:"
          run: |
            echo "set-output name=environment_identifier - $(echo '${{ github.event.issue.body }}' | grep -oP '(?<=environment_identifier:).*')"

      - name: Validate azure-region
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: azure-region
          token: ${{ secrets.GIT_TOKEN }}
          run: |
            echo "set-output name=Azure_Region - $(echo '${{ github.event.issue.body }}' | grep -oP '(?<=azure-region:).*')"  
            

      
      - name: Validate business unit
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: business-unit
          token: ${{ secrets.GIT_TOKEN }}   

      - name: Validate access connector-id
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: access-connector-id
          token: ${{ secrets.GIT_TOKEN }}


      - name: Validate user-assigned-managed-identity
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: user-assigned-managed-identity
          token: ${{ secrets.GIT_TOKEN }}

      - name: Validate workspace name
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: workspace-name
          token: ${{ secrets.GIT_TOKEN }}    

      - name: Validate number-of-azure-storage-locations
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: number-of-azure-storage-locations
          token: ${{ secrets.GIT_TOKEN }}   

      - name: Validate storage-container-url-1
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: storage-container-url-1
          token: ${{ secrets.GIT_TOKEN }} 


      - name: Validate storage-container-url-2
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: storage-container-url-2
          token: ${{ secrets.GIT_TOKEN }} 


      - name: Validate storage-container-url-3
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: storage-container-url-3
          token: ${{ secrets.GIT_TOKEN }} 

      - name: Validate storage-container-url-4
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: storage-container-url-4
          token: ${{ secrets.GIT_TOKEN }} 

      - name: Validate storage-container-url-5
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: storage-container-url-5
          token: ${{ secrets.GIT_TOKEN }}              
          
      - name: Inputs of issue
        id: inputs
        run: |
          # Parse values from the issue form
          environment_identifier="${{ github.event.issue.body | fromJson | index 'environment-identifier' }}"
          azure_region="${{ github.event.issue.body | fromJson | index 'azure-region' }}"
          business_unit="${{ github.event.issue.body | fromJson | index 'business-unit' }}"
          access_connector_id="${{ github.event.issue.body | fromJson | index 'access-connector-id' }}"
          user_assigned_managed_identity="${{ github.event.issue.body | fromJson | index 'user-assigned-managed-identity' }}"
          workspace_name="${{ github.event.issue.body | fromJson | index 'workspace-name' }}"
          storage_container_urls="${{ github.event.issue.body | fromJson | index 'storage-container-url' }}"
          owner_group="${{ github.event.issue.body | fromJson | index 'owner-group' }}"

          echo "Printing all values:"
          echo "Environment Identifier: $environment_identifier"
          echo "Azure Region: $azure_region"
          echo "Business Unit: $business_unit"
          echo "Access Connector ID: $access_connector_id"
          echo "User Assigned Managed Identity: $user_assigned_managed_identity"
          echo "Workspace Name: $workspace_name"
          echo "Owner Group: $owner_group"
          echo "Storage Container URLs: $storage_container_urls"
