# .github/workflows/validate-storage-request.yml
name: "Validate Storage Request"
on:
  issues:
    types: [opened, edited]
env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  LDAP_MS_ID: ${{ secrets.LDAP_MSID }}
  LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Issues Template Parser
        id: issues-parser
        uses: issue-ops/parser@v3.0.0
        with: 
          body: ${{ github.event.issue.body }}
          template-path: number.yml

      
      - name: Validate Environment
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: environment-identifier
          token: ${{ secrets.GIT_TOKEN }}

      - name: Validate azure-region
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with: 
          issue-form: ${{ steps.issue-parser.outputs.json }}
          section: azure-region
          token: ${{ secrets.GIT_TOKEN }}  
